Repository dailykit/HERN, pull requests merged in 2022-06, with the labels that each got.

#1000 fix: fixed recurrence link with brand when brandLocationId null
  store/src/components/kiosk/fulfillment.js
  store/src/pages/[brand]/kiosk/[id].js
Labels: bug

#1016 Feat/checkout page UI
  store/src/components/userInfo.js
  store/src/pages/[brand]/get-started/checkout.js
  store/src/sections/OrderInfo.jsx
  store/src/sections/checkout-page/index.js
  store/src/sections/select-delivery/address_section.js
  store/src/styles/components/steps-navbar.scss
  store/src/styles/main.scss
  store/src/styles/sections/subscription-checkout.scss
Labels: improvement, UI

#1019 Fix/order/sachet item title
  admin/src/apps/order/components/ProcessSachet/index.jsx
  admin/src/apps/order/utils/getRecursiveProducts.js
  admin/src/apps/order/views/Order/sections/products.jsx
  admin/src/apps/order/views/Order/sections/sachet_item.jsx
Labels: bug

#1022 Feat/plan info
  store/src/assets/icons/Cloche.js
  store/src/assets/icons/EmptyCloche.js
  store/src/assets/icons/index.js
  store/src/components/index.js
  store/src/components/plan_info.js
  store/src/graphql/queries.js
  store/src/sections/checkout-page/index.js
  store/src/sections/menu/index.js
  store/src/sections/select-delivery/delivery.js
  store/src/sections/select-menu/menu_section.js
  store/src/styles/components/plan_info.scss
  store/src/styles/main.scss
Labels: enhancement, improvement, UI

#1026 Feat/address tunnel
  store/src/components/address_list.jsx
  store/src/graphql/queries.js
  store/src/sections/select-menu/cart/fulfillment/index.jsx
  store/src/styles/components/address_list.scss
Labels: bug, enhancement

#1043 Fix/razorpay customer info issue
  store/src/components/walletTopUp/index.jsx
  store/src/components/wallet_amount.jsx
  store/src/graphql/queries.js
  store/src/lib/payment.js
  store/src/styles/components/wallet_amount.scss
  store/src/utils/getRazorpayOptions.js
Labels: bug, improvement, UI

#1051 Feat/tacobell UI
  store/src/assets/icons/ArrowLeftWithBG.js
  store/src/assets/icons/CartIcon.js
  store/src/components/kiosk/component/infoBar.js
  store/src/components/kiosk/component/modifierPopup.js
  store/src/components/kiosk/component/product.js
  store/src/components/kiosk/component/progressBar.js
  store/src/components/kiosk/fulfillment.js
  store/src/components/kiosk/header.js
  store/src/components/kiosk/menu.js
  store/src/context/cart.js
  store/src/sections/kiosk/index.js
  store/src/sections/promotionCarousel/index.js
  store/src/styles/components/kiosk.scss
Labels: bug, enhancement, improvement

#1090 fix: fixed infinite loop on select-menu of subscription
  store/src/graphql/queries.js
  store/src/sections/select-delivery/delivery_section.js
  store/src/sections/select-menu/menu.js
  store/src/sections/select-menu/state.js
Labels: bug
