Repository dailykit/HERN, pull requests merged in 2022-05, with the labels that each got.

#892 fix: handle case for unavailable wallet, loyalty points, and referral
  store/src/components/profile_sidebar.js
  store/src/pages/[brand]/account/loyalty-points.js
  store/src/pages/[brand]/account/referrals.js
  store/src/pages/[brand]/account/wallet.js
Labels: bug

#891 Fix/loyalty,Wallet & Referrals Pages UI changes
  store/src/assets/icons/EmptyReferralIll.js
  store/src/assets/icons/MyLoyaltyPoints.js
  store/src/assets/icons/Wallet.js
  store/src/assets/icons/index.js
  store/src/context/user.js
  store/src/sections/loyalty-points/index.js
  store/src/sections/referrals/index.js
  store/src/sections/wallet/index.js
  store/src/styles/sections/account/account_loyalty_points.scss
  store/src/styles/sections/account/referrals.scss
  store/src/styles/sections/account/wallet.scss
Labels: On mobile, UI

#897 fix: handle case when productOptionType is null in modifier_popup
  store/src/components/modifier_popup.jsx
Labels: bug

#899 Fix/loyalty pages design implementation
  store/src/assets/icons/Wallet.js
  store/src/assets/icons/WalletPageIllustration.js
  store/src/assets/icons/index.js
  store/src/sections/wallet/index.js
Labels: bug

#901 Fix/error in location selector
  store/src/components/header.js
  store/src/components/locationSelector/delivery.js
  store/src/components/locationSelector/dinein.js
  store/src/components/locationSelector/pickup.js
  store/src/components/locationSelector/storeList.js
  store/src/components/refineLocation.js
  store/src/context/cart.js
  store/src/sections/select-delivery/address_tunnel.js
  store/src/utils/location/utils/delivery.js
  store/src/utils/location/utils/sharedLocationUtils.js
Labels: bug

#902 fix: replace billingDetails with cartOwnerBilling
  store/src/components/cart_billing_details.js
  store/src/components/cart_order_details.js
  store/src/components/order_details.js
  store/src/sections/cart/CartDetails.js
Labels: bug

#903 fix: refactor condition when defaultOptionType is null
  store/src/components/modifier_popup.jsx
Labels: bug

#910 fix: replace balanceToPay with totalToPay in cart_billing_details
  store/src/components/cart_billing_details.js
Labels: bug

#911 fix: remove 'SEND LOGIN EMAIL' block when email already exists and show error in its place
  store/src/components/login.jsx
Labels: bug

#914 fix: fix error in clone recipe when an ingredient does not have a pro…
  admin/src/apps/products/views/Forms/RecipeForm/index.js
Labels: bug

#938 fix: toggle issue in product option
  admin/src/apps/products/views/Forms/Product/ProductOptions/index.jsx
  admin/src/apps/products/views/Forms/Product/index.jsx
  admin/src/shared/components/OperationalMode/Listing/LiveMenuBrandLocation/index.js
  admin/src/shared/components/OperationalMode/Query/index.js
Labels: bug

#958 Feat/referral button
  store/src/assets/icons/WalletPageIllustration.js
  store/src/components/product_card.jsx
  store/src/sections/order/index.js
  store/src/sections/slider-section/index.js
  store/src/sections/testimonials/index.js
  store/src/sections/wallet/index.js
  store/src/styles/sections/account/wallet.scss
  store/src/styles/sections/testimonials.scss
Labels: bug

#960 fix: remove availability check from referral, loyalty-point, and wallet's getStaticProps and apply conditions on their components
  store/src/pages/[brand]/account/loyalty-points.js
  store/src/pages/[brand]/account/referrals.js
  store/src/pages/[brand]/account/wallet.js
  store/src/sections/loyalty-points/index.js
  store/src/sections/referrals/index.js
  store/src/sections/wallet/index.js
Labels: bug

#969 feat: html parser added
  store/src/sections/slider-section/index.js
  store/src/styles/sections/slider-section.scss
Labels: improvement

#979 feat/wallet topup
  admin/src/shared/components/ConfigTemplateUI/UIComponents/index.js
  admin/src/shared/components/ConfigTemplateUI/getFieldUI.js
  admin/src/shared/graphql/index.js
  server/entities/payment/controllers/handle-payment-webhook.js
  server/entities/payment/functions/paytm/functions.js
  server/entities/payment/functions/paytm/initiatePayment.js
  server/entities/payment/functions/paytm/webhookEvents.js
  server/entities/payment/functions/razorpay/initiatePayment.js
  server/entities/payment/functions/stripe/initiatePayment.js
  server/entities/payment/graphql/query.js
  store/src/components/PayButton/index.jsx
  store/src/components/index.js
  store/src/components/paymentOptionsRenderer/components/AddCard/index.jsx
  store/src/components/paymentOptionsRenderer/index.jsx
  store/src/components/paymentProcessingModal/index.jsx
  store/src/components/walletTopUp/index.jsx
  store/src/graphql/mutations.js
  store/src/graphql/queries.js
  store/src/lib/payment.js
  store/src/sections/wallet/index.js
  store/src/styles/components/wallet-top-up.scss
  store/src/styles/globals.css
  store/src/styles/main.scss
  store/src/utils/renderComponentByName.js
Labels: enhancement

#988 fix: more then 100% discount in products and in their options
  admin/src/apps/products/views/Forms/Product/ProductOptions/index.jsx
  admin/src/apps/products/views/Forms/Product/components/Pricing/index.jsx
Labels: bug

#990 fix: fixed referral invite link working
  store/src/components/login.jsx
  store/src/sections/login/index.js
  store/src/utils/useQueryParams.js
Labels: bug

#995 Fix/product price on product page
  store/src/components/modifier_popup.jsx
  store/src/sections/product/index.js
Labels: bug

#996 Feat/subscription menu new UI
  store/src/assets/icons/Chevron.jsx
  store/src/components/cart_product.jsx
  store/src/components/index.js
  store/src/components/page_banner.js
  store/src/components/tunnel.js
  store/src/sections/OrderInfo.jsx
  store/src/sections/menu/index.js
  store/src/sections/select-menu/cart/PaymentCard/index.jsx
  store/src/sections/select-menu/cart/billing/index.jsx
  store/src/sections/select-menu/cart/fulfillment/index.jsx
  store/src/sections/select-menu/cart/index.jsx
  store/src/sections/select-menu/cart/products/AddOnProducts.jsx
  store/src/sections/select-menu/cart/products/PlanProducts.jsx
  store/src/sections/select-menu/menu.js
  store/src/sections/select-menu/menu_section.js
  store/src/sections/select-menu/week_picker.js
  store/src/styles/cart/cart_billing.scss
  store/src/styles/cart/fulfillment.scss
  store/src/styles/components/billing.scss
  store/src/styles/components/cart_product.scss
  store/src/styles/components/coupon.scss
  store/src/styles/components/loyalty_points.scss
  store/src/styles/components/page_banner.scss
  store/src/styles/components/product_skeleton.scss
  store/src/styles/components/wallet_amount.scss
  store/src/styles/main.scss
  store/src/styles/sections/order-info.scss
  store/src/styles/sections/select-menu.scss
Labels: improvement

#998 fix: fixed price overflow in UI on order page and price wrap in UI on product page in mobile view
  store/src/components/modifier_popup.jsx
  store/src/styles/components/product_card.scss
  store/src/styles/sections/order.scss
  store/src/styles/sections/product.scss
Labels: UI
