Repository dailykit/HERN, pull requests merged in 2022-04, with the labels that each got.

#695 feat: added coupon selector field for ConfigTemplateUI
  admin/src/shared/components/ConfigTemplateUI/UIComponents/index.js
  admin/src/shared/components/ConfigTemplateUI/getFieldUI.js
Labels: enhancement

#702 Feat/faq section
  store/src/components/login.jsx
  store/src/graphql/queries.js
  store/src/lang/ar.json
  store/src/lang/en.json
  store/src/sections/Faq/index.js
  store/src/sections/FaqSection/index.js
  store/src/sections/contact-us/index.js
  store/src/sections/faq-section/index.js
  store/src/sections/product-gallery/index.js
  store/src/styles/components/header.scss
  store/src/styles/main.scss
  store/src/styles/sections/faq.scss
  store/src/styles/sections/onDemandCart.scss
  store/src/styles/sections/product-gallery.scss
  store/src/utils/renderComponentByName.js
Labels: bug, enhancement

#704 fix: error message and graphql subscription in coupon selector
  admin/src/shared/components/ConfigTemplateUI/UIComponents/index.js
  admin/src/shared/graphql/index.js
Labels: improvement

#714 Fix/product gallery css
  store/src/sections/product-gallery/index.js
  store/src/styles/sections/product-gallery.scss
Labels: bug

#719 feat: added campaign selector for ConfigTemplateUI
  admin/src/shared/components/ConfigTemplateUI/UIComponents/index.js
  admin/src/shared/components/ConfigTemplateUI/getFieldUI.js
  admin/src/shared/graphql/index.js
Labels: enhancement

#721 fix: faq font, responsiveness and size
  store/src/sections/faq-section/index.js
  store/src/styles/sections/faq.scss
Labels: bug

#728 Feat/login wrapper page
  store/src/components/header.js
  store/src/components/login.jsx
  store/src/components/loyalty_points.jsx
  store/src/components/templateFile.js
  store/src/pages/[brand]/account/addresses.js
  store/src/pages/[brand]/account/cards.js
  store/src/pages/[brand]/account/loyalty-points.js
  store/src/pages/[brand]/account/orders.js
  store/src/pages/[brand]/account/profile.js
  store/src/pages/[brand]/account/referrals.js
  store/src/pages/[brand]/account/subscriptions.js
  store/src/pages/[brand]/account/wallet.js
  store/src/pages/[brand]/get-started/checkout.js
  store/src/pages/[brand]/get-started/select-delivery.js
  store/src/pages/[brand]/get-started/select-menu.js
  store/src/pages/[brand]/get-started/select-plan.js
  store/src/pages/[brand]/menu.js
  store/src/sections/login/index.js
  store/src/styles/components/header.scss
  store/src/styles/components/login_v1.scss
  store/src/utils/loginWrapper.js
  store/src/utils/renderComponentByName.js
Labels: enhancement

#734 Feat/radio button config UI
  admin/src/shared/components/ConfigTemplateUI/UIComponents/index.js
  admin/src/shared/components/ConfigTemplateUI/getFieldUI.js
Labels: enhancement

#744 Feat/delivery tracking module
  store/package.json
  store/src/assets/icons/DeliveryInfoIcons.js
  store/src/assets/icons/index.js
  store/src/components/cart_order_details.js
  store/src/graphql/queries.js
  store/src/styles/components/delivery_progress.scss
  store/src/styles/main.scss
Labels: enhancement

#749 Fix/handle no items
  store/src/assets/icons/EmptyCloche.js
  store/src/assets/icons/EmptyStore.js
  store/src/assets/icons/index.js
  store/src/components/empty.js
  store/src/components/index.js
  store/src/sections/cart/index.js
  store/src/sections/featuredCollection/index.js
  store/src/sections/order-history/index.js
  store/src/sections/order/index.js
  store/src/styles/components/empty.scss
  store/src/styles/main.scss
Labels: bug, enhancement

#762 fix:UI improvement on menu page
  store/src/styles/components/product_card.scss
Labels: bug

#757 fix: fix add reward tunnel for campaign
  admin/src/apps/crm/views/Forms/Campaign/tunnels/Rewards/index.js
Labels: bug

#758 fix: fixed wallet page in customer account section
  store/src/sections/wallet/index.js
  store/src/styles/sections/account/wallet.scss
Labels: bug

#759 fix: html and module CSS and JS file link
  store/src/utils/getPageProps.js
Labels: bug

#761 Make empty store illustration responsive
  store/src/assets/icons/EmptyStore.js
Labels: bug

#769 fix: referrals name empty
  store/src/components/userType.js
  store/src/sections/referrals/index.js
  store/src/styles/sections/account/referrals.scss
Labels: bug

#768 fix: fixed refer customer feature
  store/src/components/login.jsx
  store/src/context/user.js
Labels: bug

#775 Referral link, exposed OTP
  store/src/components/login.jsx
  store/src/graphql/mutations.js
  store/src/sections/referrals/index.js
  store/src/utils/useQueryParams.js
Labels: bug, enhancement

#786 Fix/update wallet page UI
  store/src/sections/wallet/index.js
  store/src/styles/sections/account/wallet.scss
  store/src/utils/formatCurrency.js
Labels: improvement

#777 Fix/UI ingredients form in recipe app
  admin/src/shared/components/Sidebar/styled.js
Labels: bug

#787 Feat/referral page new design
  store/src/assets/icons/EmptyReferralIll.js
  store/src/assets/icons/index.js
  store/src/sections/referrals/index.js
  store/src/styles/sections/account/referrals.scss
Labels: improvement

#791 fix: close prop is not passing
  admin/src/apps/crm/views/Listings/CouponListing/index.js
Labels: bug

#790 fix: checkout page login ui
  store/src/assets/icons/LeftArrow.js
  store/src/components/userType.js
  store/src/sections/cart/index.js
  store/src/styles/components/userInfo.scss
Labels: bug

#804 fix: not rendering otp field
  store/src/components/login.jsx
Labels: bug

#802 fix: fix wallet usage in cart
  server/entities/payment/controllers/handle-cart-payment.js
  server/entities/payment/graphql/query.js
  store/src/components/cart_billing_details.js
  store/src/components/cart_order_details.js
  store/src/components/login.jsx
  store/src/context/user.js
  store/src/graphql/queries.js
  store/src/sections/cart/CartDetails.js
  store/src/sections/cart/index.js
  store/src/styles/cart/fulfillment.scss
Labels: bug, improvement

#825 fix: otp incorrect error on using an existing email in registration
  store/src/components/login.jsx
Labels: bug

#816 Fix/loyalty points flow
  store/src/components/loyalty_points.jsx
  store/src/sections/loyalty-points/index.js
Labels: bug

#867 Fix/billing details
  store/src/components/modifierOptionCard.js
  store/src/components/modifier_popup.jsx
  store/src/components/product_card.jsx
  store/src/sections/featuredCollection/productCustomArea.js
  store/src/sections/order/index.js
  store/src/sections/product/index.js
  store/src/styles/components/product_card.scss
Labels: bug

#870 fix: fixed default Option type selection in product modifier
  store/src/components/modifier_popup.jsx
Labels: bug
