Repository dailykit/HERN, pull requests merged in 2022-03, with the labels that each got.

#567 fix: fixed error while closing create collection and coupon tunnels
  admin/src/apps/crm/views/Listings/CouponListing/index.js
  admin/src/apps/menu/views/Listings/CollectionsListing/index.js
  admin/src/shared/CreateUtils/Menu/createCollection.js
  admin/src/shared/CreateUtils/crm/createCoupon.js
Labels: bug

#571 tweak: set config by getSetting function
  store/src/components/layout.js
  store/src/components/loyalty_points.jsx
  store/src/components/modifier_popup.jsx
  store/src/components/profile_sidebar.js
  store/src/components/steps_navbar.js
  store/src/lib/config.js
  store/src/lib/payment.js
  store/src/pages/[brand]/kiosk/[id].js
  store/src/sections/cart/CartDetails.js
  store/src/sections/privacy-policy/index.js
  store/src/sections/profile/index.js
  store/src/sections/refund-policy/index.js
  store/src/sections/terms-condition/index.js
  store/src/utils/getSettings.js
Labels: enhancement

#612 fix: updated contact us config and ui
  store/src/sections/contact-us/index.js
  store/src/styles/sections/contact-us.scss
Labels: bug

#613 fix: update carousel dots alignment
  store/src/styles/sections/slider-section-2.scss
Labels: UI

#614 fix: update config pattern in product gallery component
  store/src/sections/product-gallery/index.js
Labels: improvement

#639 feat: Added new style variant for testimonial system component
  store/src/sections/testimonials/index.js
  store/src/styles/sections/testimonials.scss
Labels: UI

#651 fix: added 404 page
  store/src/pages/404.js
Labels: bug

#654 Fix/product page issues
  store/src/sections/product/index.js
  store/src/styles/sections/product.scss
Labels: bug

#662 Fix/small UI updates in breezychef
  store/src/sections/product-gallery/index.js
  store/src/styles/components/header.scss
  store/src/styles/sections/product-gallery.scss
Labels: UI

#663 Fix/update testimonial and slider section
  store/src/sections/slider-section/index.js
  store/src/sections/testimonials/index.js
  store/src/styles/sections/testimonials.scss
Labels: bug, UI

#667 Fix/loyalty points and referrals
  store/src/pages/[brand]/account/loyalty-points.js
  store/src/sections/loyalty-points/index.js
  store/src/sections/product-gallery/index.js
  store/src/sections/referrals/index.js
  store/src/styles/sections/product-gallery.scss
Labels: bug

#664 fix: UI and Validation update in Login and Register forms
  store/src/components/login.jsx
  store/src/styles/components/login_v1.scss
Labels: UI

#666 fix: links not working for translation
  store/src/components/header.js
  store/src/sections/cart/CartDetails.js
  store/src/sections/cart/index.js
Labels: bug

#668 Feat/debounce remove button
  store/src/context/cart.js
  store/src/sections/featuredCollection/productCustomArea.js
Labels: bug

#670 Form validation on OTP and first name and last Name
  store/package.json
  store/src/components/login.jsx
  store/src/sections/profile/index.js
  store/src/styles/components/login_v1.scss
  store/src/styles/sections/account/profile.scss
Labels: bug

#671 Feat/query state login
  store/src/components/header.js
  store/src/components/layout.js
  store/src/components/login.jsx
  store/src/lib/config.js
  store/src/utils/loginWrapper.js
Labels: enhancement

#672 fix: goto-menu-button-in-cart
  store/src/sections/cart/index.js
Labels: bug

#673 fix: otp length should be 6, special characters and alphabets are not allowed
  store/src/components/login.jsx
Labels: bug

#674 fix: error message in phone number field of login and register
  store/src/components/login.jsx
Labels: bug

#677 Feat/server/send otp
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/hasura-migration.md
  .github/ISSUE_TEMPLATE/user-story.md
  .github/Pull_request_template.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/rebase.yml
  server/entities/events/index.js
  server/entities/events/sendOtp.js
  server/index.js
Labels: bug, enhancement

#678 Feat/hover
  store/src/components/header.js
  store/src/components/navbar/index.jsx
  store/src/sections/featuredCollection/productCustomArea.js
  store/src/styles/components/header.scss
  store/src/styles/components/on_demand_menu.scss
  store/src/styles/sections/order.scss
Labels: enhancement

#676 feat: added activeColor in config for arrow colors on click in Product-Gallery component
  store/src/sections/product-gallery/index.js
  store/src/styles/sections/product-gallery.scss
Labels: UI

#680 fix: resend otp
  server/entities/events/index.js
  server/entities/events/sendOtp.js
  server/index.js
Labels: bug

#689 fix: font size
  store/src/styles/sections/contact-us.scss
  store/src/styles/sections/featured-coupon.scss
  store/src/styles/sections/product-gallery.scss
  store/src/styles/sections/slider-section-2.scss
  store/src/styles/sections/testimonials.scss
Labels: bug
