Repository dailykit/HERN, pull requests merged in 2022-07, with the labels that each got.

#1103 feat: token for otp auth
  server/entities/auth/controllers.js
  server/entities/auth/graphql/index.js
  server/entities/auth/graphql/mutations.js
  server/entities/auth/graphql/queries.js
  server/entities/auth/index.js
  server/entities/auth/routes.js
  server/entities/index.js
  server/index.js
Labels: enhancement

#1122 Feat/pinelabs integration
  server/entities/payment/controllers/handle-payment-webhook.js
  server/entities/payment/controllers/handle-paytm-qr-webhook.js
  server/entities/payment/controllers/index.js
  server/entities/payment/functions/pineLabs/functions.js
  server/entities/payment/functions/pineLabs/index.js
  server/entities/payment/functions/pineLabs/initiatePayment.js
  server/entities/payment/functions/pineLabs/webhookEvents.js
  server/entities/payment/graphql/query.js
  server/entities/payment/route.js
  server/utils/paymentLogger.js
  store/src/utils/useTerminalPay.js
Labels: enhancement

#1128 Feat/related products
  store/src/components/kiosk/component/modifierPopup.js
  store/src/components/kiosk/component/product.js
  store/src/context/cart.js
  store/src/graphql/queries.js
Labels: enhancement, improvement

#1129 fix: handle razorpay failed status in webhook request
  server/entities/payment/functions/razorpay/webhookEvents.js
  server/utils/paymentLogger.js
Labels: bug

#1134 feat: created video uploader component for config
  admin/src/shared/components/AssetUploader/Upload.jsx
  admin/src/shared/components/ConfigTemplateUI/UIComponents/index.js
  admin/src/shared/components/ConfigTemplateUI/getFieldUI.js
Labels: enhancement

#1135 feat: created a custom field for config
  admin/src/shared/components/ConfigTemplateUI/UIComponents/index.js
  admin/src/shared/components/ConfigTemplateUI/getFieldUI.js
  admin/src/shared/components/ConfigTemplateUI/index.js
  admin/src/shared/components/ErrorState/index.jsx
Labels: enhancement

#1145 fix: undefined when clicking 0
  store/src/components/kiosk/fulfillment.js
Labels: bug

#1150 fix: fixed customer not able to register with mobile app
  server/entities/auth/controllers.js
Labels: bug

#1159 Fix/phone no redirect to menu page
  store/src/components/kiosk/component/PhoneNumberTunnel.js
  store/src/components/paymentProcessingModal/index.jsx
  store/src/components/paymentProcessingModal/styles.js
  store/src/lib/payment.js
Labels: bug

#1171 Cart items spacing, scrolling issue and notification after adding from product Gallery
  store/src/components/kiosk/cart.js
  store/src/components/kiosk/component/modifierPopup.js
  store/src/components/kiosk/component/productGallery.js
  store/src/graphql/queries.js
  store/src/styles/components/kiosk.scss
  store/src/utils/cartItemsCombine.js
Labels: bug, improvement

#1177 fix: auto scroll issue inside menu category | kiosk
  store/src/components/kiosk/menu.js
Labels: improvement

#1181 Feat/convert meal product admin UI
  admin/src/apps/products/graphql/products.js
  admin/src/apps/products/views/Forms/Product/index.jsx
Labels: enhancement

#1187 feat: added pinelabs wired integration
  store/src/lib/payment.js
  store/src/utils/index.js
  store/src/utils/usePineLabsTerminalPay.js
Labels: enhancement

#1189 Promotional screen after dine in or take out
  store/src/components/kiosk/component/progressBar.js
  store/src/components/kiosk/fulfillment.js
Labels: enhancement

#1191 Table selection number pad view
  store/src/components/kiosk/component/dineInTableView.js
  store/src/styles/components/kiosk.scss
Labels: enhancement

#1194 Feat/table view
  store/src/components/kiosk/component/PhoneNumberTunnel.js
  store/src/components/kiosk/component/dineInTableView.js
Labels: bug

#1195 fix: fix the response parsing format for pinelabs wired integration
  store/src/utils/usePineLabsTerminalPay.js
Labels: bug

#1205 Cart page UI and PayInCash Modal
  admin/src/apps/products/views/Forms/Product/index.jsx
  store/src/components/kiosk/cart.js
  store/src/components/kiosk/component/progressBar.js
  store/src/components/kiosk/fulfillment.js
  store/src/context/cart.js
  store/src/graphql/queries.js
  store/src/utils/cartItemsCombine.js
Labels: enhancement
